# ckan-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ckan-ingress
  namespace: cmr-avre-team
  annotations:
    kubernetes.io/ingress.class: "alb"
spec:
  rules:
  - host: ckan.dorfak-group.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ckan
            port:
              number: 5000
