apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.global.appName}}-{{ .Release.Name }}-secrets
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
