apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.global.appName}}-{{ .Release.Name }}-secrets
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc | quote }}
  CKAN_DB_USER: {{ .Values.secrets.CKAN_DB_USER | b64enc | quote }}
  CKAN_DB_PASSWORD: {{ .Values.secrets.CKAN_DB_PASSWORD | b64enc | quote }}
  DATASTORE_READONLY_USER: {{ .Values.secrets.DATASTORE_READONLY_USER | b64enc | quote }}
  DATASTORE_READONLY_PASSWORD: {{ .Values.secrets.DATASTORE_READONLY_PASSWORD | b64enc | quote }}
  CKAN___BEAKER__SESSION__SECRET: {{ .Values.secrets.CKAN___BEAKER__SESSION__SECRET | b64enc | quote }}
  CKAN___API_TOKEN__JWT__ENCODE__SECRET: {{ .Values.secrets.CKAN___API_TOKEN__JWT__ENCODE__SECRET | b64enc | quote }}
  CKAN_SYSADMIN_NAME: {{ .Values.secrets.CKAN_SYSADMIN_NAME | b64enc | quote }}
  CKAN_SYSADMIN_PASSWORD: {{ .Values.secrets.CKAN_SYSADMIN_PASSWORD | b64enc | quote }}
  CKAN_SYSADMIN_EMAIL: {{ .Values.secrets.CKAN_SYSADMIN_EMAIL | b64enc | quote }}
  CKAN_SMTP_USER: {{ .Values.secrets.CKAN_SMTP_USER | b64enc | quote }}
  CKAN_SMTP_PASSWORD: {{ .Values.secrets.CKAN_SMTP_PASSWORD | b64enc | quote }}
  CKANEXT_OIDC_PKCE_CLIENT_ID: {{ .Values.secrets.CKANEXT_OIDC_PKCE_CLIENT_ID | b64enc | quote }}
  CKANEXT_OIDC_PKCE_CLIENT_SECRET: {{ .Values.secrets.CKANEXT_OIDC_PKCE_CLIENT_SECRET | b64enc | quote }}

  CKAN_SQLALCHEMY_URL: {{ .Values.secrets.CKAN_SQLALCHEMY_URL | b64enc | quote }}
  CKAN_DATASTORE_WRITE_URL: {{ .Values.secrets.CKAN_DATASTORE_WRITE_URL | b64enc | quote }}
  CKAN_DATASTORE_READ_URL: {{ .Values.secrets.CKAN_DATASTORE_READ_URL | b64enc | quote }}

  # TEST_CKAN_SQLALCHEMY_URL: postgres://ckan:ckan@db/ckan_test
  # TEST_CKAN_DATASTORE_WRITE_URL: postgresql://ckan:ckan@db/datastore_test
  # TEST_CKAN_DATASTORE_READ_URL: postgresql://datastore_ro:datastore@db/datastore_test
