apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ckan-helm.ckan.fullname" . }}
  labels:
    {{- include "ckan-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ckan.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "ckan-helm.ckan.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "ckan-helm.ckan.fullname" . }}
    spec:
      # initContainers:
      # - name: ckan-volume-permissions
      #   image: busybox
      #   command: ['sh', '-c', 'chown -R 0:0 /var/lib/ckan']
      #   volumeMounts:
      #   - mountPath: /var/lib/ckan
      #     name: ckan-storage
      containers:
      - name: ckan
        image: "{{ .Values.ckan.image.repository }}:{{ .Values.ckan.image.tag }}"
        ports:
        - name: ckan
          containerPort: {{ .Values.ckan.service.port }}
        resources:
          {{- toYaml .Values.ckan.resources | nindent 12 }}
        envFrom:
          - configMapRef:
              name: {{.Values.global.appName}}-{{ .Release.Name }}-config
          - secretRef:
              name: {{.Values.global.appName}}-{{ .Release.Name }}-secrets
      #   volumeMounts:
      #   - name: ckan-storage
      #     mountPath: /var/lib/ckan
      # volumes:
      #   - name: ckan-storage
      #     persistentVolumeClaim:
      #       claimName: {{ include "ckan-helm.ckan.fullname" . }}-pvc

