# ckan-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ckan-helm.ckan.fullname" . }}-pvc
spec:
    accessModes:
    - {{ .Values.ckan.persistence.accessMode }}
    resources:
      requests:
        storage: {{ .Values.ckan.persistence.size }}
    storageClassName: {{ .Values.ckan.persistence.storageClass | quote }}
