
name: Build Docker Image

on:
  push:
    branches:
      - master
      - dev
      # - build-pipeline
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./ckan
          file: ./ckan/Dockerfile
          push: true
          tags: |
            benmotevalli/ckan-auscope:${{ github.ref == 'refs/heads/master' && 'latest' || 'dev' }}
