name: Build - Dev and Prod Images

on:
  push:
    branches:
      - master
      - dev-sample

jobs:

  build-and-push-ghcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.TOKEN }}

      - name: Set dynamic tag
        id: set-tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev-sample" ]]; then
            echo "::set-output name=tag::ghcr.io/auscope/auscope-ckan-dev:sample-latest"
          else
            echo "::set-output name=tag::ghcr.io/auscope/auscope-ckan-dev:latest"
          fi

      - name: Build and Push Docker image to GHCR
        uses: docker/build-push-action@v2
        with:
          context: ./ckan
          file: ./ckan/Dockerfile # Consider using a separate Dockerfile for dev if needed
          tags: ${{ steps.set-tag.outputs.tag }}
          push: true
          load: false # Ensure it's set to false to use Buildx's capabilities
          no-cache: true # Optional to avoid using any cached layers
          outputs: type=docker # Ensures the output is optimized for Docker
